### ISSUE TITLE
List of Tables, List of Figures, and Contents Not Capitalized

### ISSUE THREAD

**Issue by JustinShultz** [bgranzow/rpi_thesis_template#1]
I was recommended to use your templates from Susan Palmer at the OGE. They are very helpful, thank you. However I am having a problem with capitalizing the Table of Contents, List of Tables, and List of Figures. 

The template and generated PDF do not have the lists capitalized, though they need to be. I tried solving the problem myself and found little success. Can anyone change the files so that those sections are capitalized?

**Comment by bgranzow** [comment]
Commit 5546ed0225a addresses this.
I have no idea what actually caused the issue though. I replaced the `thesis.tex` preamble to be a lot closer to what I actually used in my document and it went away, so that might be a hint.

**Comment by JustinShultz** [comment]
@bgranzow Thank you very much! I particularly appreciate your quick response as I am rushing to finish up my dissertation. 
Best Regards,
Justin
